miekg/gitopper

main.go, server.go
This commit adapts the main entrypoint and control loops it starts
to be context interruptible due to an open TODO.  There is more that
can be done.
=> main: make context-controlled and interruptible.

config, gitcmd/git.go, server.go
Was broken because no tests...
=> Fix specific branch pulling

README.md, config.go, config_test.go, main.go
- tagline
- Fix various TODO items
=> restart on change

main.go, osutil/hostname.go, router.go
=> Factor hostname stuff into osutil - as used multiple times

README.md, cmd/gitopperctl/README.md, cmd/gitopperctl/main.go
=> polish docs a bit

README.md, main.go
=> Add -P flag to force newest repo when bootstrapping

.gitignore, flag.go, flag_test.go, go.mod, go.sum, main.go, main_test.go, ssh.go
In order to test on my local machine, I need to swap out some of the
binary's dependencies with test doubles.  I've started by making the
basic inputs into the binary the flags something contained in a
struct whose values can be dereferenced and explicitly passed.
=> main: refactor entrypoint to support testing.

README.md
=> fix docs too

cmd/gitopperctl/README.md, cmd/gitopperctl/main.go
=> Add -m flag to expose the json directly

server.go
This sets the start time of a process to what systemd report. This help in setting the initial status of service.
This setting of state can now also pulled out of the loop in trackService.
Closes: #29
=> Add SetBoot

ssh.go
pull out the check if the service is for this host and target, should save a few lines.
=> services: refactor slightly

main.go
When the controller context is cancelled and the worker goroutines have
ceased serving, the HTTP serving interface should attempt a graceful
shutdown, but not before.  This pattern sets the stage for probable
application of the same to the SSH interface.
There are a few potential avenues for additional cleanups around
monitoring interface setup and context plumbing that should be explored
independently.  I wanted to keep the code delta as small as possible
in case I made any mistakes.
=> main: gracefully cease HTTP serving on shutdown.

main.go
Move the setting up of of ssh and http routers until after the services
are done. This correctly sets up the workerWG waitgroup and makes the
ssh/http correctly wait for them instead of stopping at startup.
=> Fix stopping the process

server.go
=> Add jitter to pull duration

gitcmd/git.go, gitcmd/git_test.go, ssh.go
=> Use 8 chars git hash values

main.go
Add a fake goroutine so the waitgroups work and everything get correctly
canceled and stops.
=> Fix shutdown

README.md, gitcmd/git.go, main.go, server.go, ssh.go
In ssh also log the path to the public key. Remove the 'machine' from
the server.go logging and just mention the service which is the
important bit here.
=> Better logging

gitcmd/git.go
=> Stash local changes before pulling or rolling back

main.go
=> More Machine -> Service in logging

main.go, main_test.go
=> Allow non-root runs

README.md
=> Small doc update

README.md, cmd/gitopperctl/README.md, cmd/gitopperctl/main.go, server.go, ssh.go
=> Add pull now operation

cmd/gitopperctl/README.md, cmd/gitopperctl/main.go, ssh.go
Better conveys the we are performing and action and shorter
=> Rename state to do in the protocol

main.go
When bootstrapping and -P specified, don't error out when we do have the
repo, startup and pull the changes later.
=> Don't fatal on pull fail on boot

main.go
=> Check for duplicate services

cmd/gitopperctl/README.md, cmd/gitopperctl/main.go, config.toml, main.go, proto/proto.go, ssh.go
nice idea, but still wont reach the right persons
=> revert a6fb787

cmd/gitopperhdr/main.go, gitcmd/git.go
=> Add branch in giturl

cmd/gitopperctl/main.go, config.go, server.go, ssh.go
This commit provides several small cleanups:
* Extraction of command line behavior into dedicated functions for less
nested indentation.
* Applying the mutex hat on the fields it protects.
* Note the direction of the channels.
=> main: small cleanups.

main.go, server.go
Without a daemon-reload systemd won't see changes on disk.
=> Handle changed units.

main.go, server.go
Noticed that gitopperctl output does not update the status.
=> Clear errors
